const kurlyDB = [
    {
        src:'./images/kurly_001.jpg',
        name:'[해태] 여름 시즌 한정 트로피컬 에디션 간식 4종 (택1)',
        summary:'새콤달콤한 여름맛 간식',
        price:3580,
        sale:7,
        review:154,
    },
    {
        src:'./images/kurly_002.jpg',
        name:'[피자로빈슨] 뉴욕 메가 슬라이스 피자 페퍼로니',
        summary:'짭쪼름한 페퍼로니가 듬뿍',
        price:5500,
        sale:20,
        review:18,
    },
    {
        src:'./images/kurly_003.jpg',
        name:'[오리온] 꼬북칩 초코츄러스맛',
        summary:'바삭바삭한 초코 츄러스의 달콤함',
        price:1980,
        sale:10,
        review:87,
    },
    {
        src:'./images/kurly_004.jpg',
        name:'[풀무원] 얇은피 꽉찬속 만두 김치',
        summary:'매콤한 김치와 얇은 피의 환상 조합',
        price:4980,
        sale:15,
        review:312,
    },
    {
        src:'./images/kurly_005.jpg',
        name:'[빙그레] 바나나맛우유 기획팩 (6입)',
        summary:'부드럽고 달콤한 바나나맛',
        price:3980,
        sale:5,
        review:142,
    },
    {
        src:'./images/kurly_006.jpg',
        name:'[농심] 신라면 블랙 컵라면 (3입)',
        summary:'깊고 진한 육수의 프리미엄 컵라면',
        price:4500,
        sale:12,
        review:221,
    },
    {
        src:'./images/kurly_007.jpg',
        name:'[CJ제일제당] 비비고 왕교자 (1.05kg)',
        summary:'풍성한 속이 가득 찬 교자 만두',
        price:10900,
        sale:25,
        review:520,
    },
    {
        src:'./images/kurly_008.jpg',
        name:'[매일유업] 상하목장 유기농 우유 (900ml)',
        summary:'신선한 유기농 원유 100%',
        price:4200,
        sale:8,
        review:76,
    },
    {
        src:'./images/kurly_009.jpg',
        name:'[서울우유] 멸균우유 200ml x 24팩',
        summary:'실온 보관 가능한 멸균 우유',
        price:14900,
        sale:18,
        review:198,
    },
    {
        src:'./images/kurly_010.jpg',
        name:'[삼양] 불닭볶음면 (5입)',
        summary:'화끈하게 매운 중독성 강한 맛',
        price:4180,
        sale:10,
        review:345,
    },
    {
        src:'./images/kurly_011.jpg',
        name:'[동원] 리챔 클래식 (200g x 3)',
        summary:'풍부한 육즙과 부드러운 식감',
        price:5980,
        sale:15,
        review:113,
    },
    {
        src:'./images/kurly_012.jpg',
        name:'[롯데] 빼빼로 초코 (47g x 10개입)',
        summary:'국민 간식 빼빼로의 클래식 맛',
        price:7900,
        sale:20,
        review:189,
    }
    
]